import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { Button } from "../components/atoms";
import { Container, Layout, Navbar, Section } from "../components";

const Home: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>DoYourThing</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<Section>
					<Container>
						<h1 className="text-6xl font-bold">
							Welcome to{" "}
							<a href="https://github.com/milovangudelj/doyourthing">
								DoYourThing!
							</a>
						</h1>
						<p className="text-lg mt-4 max-w-[45ch]">
							A script that installs for you all your programs and
							packages as well as some system configurations that you
							define.
						</p>
						<Button>
							<a
								href="https://github.com/milovangudelj/doyourthing"
								target="_blank"
								rel="noreferrer noopener"
							>
								Learn more
							</a>
						</Button>
					</Container>
				</Section>
			</main>
		</Layout>
	);
};

export default Home;
